openapi:
  application:
    description: ${OPENAPI_DESCRIPTION:Exemplo de relatórios com JasperReport}
    version: ${OPENAPI_VERSION:1.0.0}
    title: ${OPENAPI_TITLE:JasperReport}

report:
  jasper: /report
  logo: /report/logo.png
  logo-coffee: /report/coffee_stain.png
  client-simple: /report/client/simple
  client-details: /report/client/details

server:
  servlet:
    encoding:
      charset: UTF-8
    context-path: ${CONTEXT_PATH:/jasperreport/api/v1}
  port: ${SERVER_PORT:8083}

spring:
  messages:
    encoding: utf-8
    basename: i18n.message
  jackson:
    deserialization:
      fail-on-unknown-properties: false
  data:
    web:
      pageable:
        default-page-size: 20
        max-page-size: 100
        one-indexed-parameters: false
        page-parameter: page
        size-parameter: size
      sort:
        sort-parameter: sort
  application:
    name: paginator
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jasperreport?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  flyway:
    url: jdbc:mysql://localhost:3306/jasperreport?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
    user: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}